### ISSUE TITLE
Missing usage documentation

### ISSUE THREAD

**Issue by asecondwill** [solidusio-contrib/solidus_reports#27]
Is there documentation available for this? how do we 

"build custom reports right in your store’s backend" 

?

**Comment by aldesantis** [comment]
Hey @asecondwill, you can look at the existing `ReportsController` and `sales_total` report in there. In particular, see lines [27](https://github.com/solidusio-contrib/solidus_reports/blob/master/app/controllers/spree/admin/reports_controller.rb#L27) and [34](https://github.com/solidusio-contrib/solidus_reports/blob/master/app/controllers/spree/admin/reports_controller.rb#L34).

With that said, if you need complex reporting functionality and you expect to be scaling aggressively there, I suggest going with an external business intelligence tool such as Tableau or Looker. They are way more specialized and performant and they both allow you to embed views inside other pages, which means you can still have your reports in the backend.

I'm closing this since it's a support request and not an actual issue, but feel free to continue the conversation in Slack!

**Comment by asecondwill** [comment]
Thanks for this, but I think it is an issue, there should be enough docs in the Readme to get going.

**Comment by aldesantis** [comment]
Agreed, I have renamed and reopened the issue.

**Comment by asecondwill** [comment]
https://github.com/solidusio-contrib/solidus_reports/pull/28

I made a start with some notes based on what I did to get going.
